In [1]:
import pandas as pd
import numpy as np

In [2]:
ds=pd.read_csv("bank.csv")

In [3]:
ds.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
ds.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds["deposit"] = le.fit_transform(ds["deposit"])

In [6]:
ds.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome  deposit  
0  unknown    5   may      1042         1     -1         0  unknown        1  
1  unknown    5   may      1467         1     -1         0  unknown        1  
2  unknown    5   may      1389         1     -1         0  unknown        1  
3  unknown    5   may       579         1     -1         0  unknown        1  
4  unknown    5   may       673         2     -1         0  unknown        1  
5  unknown    5   may       562         2     -1         0  unknown        1  
6  unknown    6   may      1201         1     -1         0  unknown        1  
7  unknown    6   may      1030         1     -1         0  unknown        1  
8  unknown    6   may       608         1     -1         0  unknown        1  
9  unknown    6   may      1297         3     -1         0  unknown        1

In [7]:
x = ds.iloc[:,0:16].values
y = ds.iloc[:,16].values

In [8]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [9]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [12]:
x.shape

(11162, 51)

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[1,2,3,4,6,7,8,10,15])],remainder = "passthrough")  #converts data to binary format
x = ct.fit_transform(x)

C:\Users\Amith Paavan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [14]:
x

array([[1.0, 0.0, 1.0, ..., 1, -1, 0],
       [1.0, 0.0, 1.0, ..., 1, -1, 0],
       [1.0, 0.0, 1.0, ..., 1, -1, 0],
       ...,
       [1.0, 0.0, 1.0, ..., 2, -1, 0],
       [1.0, 0.0, 1.0, ..., 2, 172, 5],
       [1.0, 0.0, 1.0, ..., 1, -1, 0]], dtype=object)

In [15]:
x.shape

(11162, 60)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10000)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [18]:
x_test

array([[ 0.44565054, -0.44565054,  0.19150966, ...,  0.88963344,
        -0.50714558, -0.40546216],
       [-2.24391068,  2.24391068,  0.19150966, ..., -0.51602831,
        -0.50714558, -0.40546216],
       [ 0.44565054, -0.44565054,  0.19150966, ..., -0.51602831,
         1.14656309,  0.50585843],
       ...,
       [ 0.44565054, -0.44565054,  0.19150966, ..., -0.16461288,
        -0.50714558, -0.40546216],
       [ 0.44565054, -0.44565054,  0.19150966, ..., -0.51602831,
        -0.50714558, -0.40546216],
       [ 0.44565054, -0.44565054,  0.19150966, ...,  1.24104888,
        -0.50714558, -0.40546216]])

In [19]:
from sklearn.linear_model import LogisticRegression
logr = LogisticRegression()
logr.fit(x_train,y_train)

C:\Users\Amith Paavan\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
ypred = logr.predict(x_test)

In [21]:
ypred

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
y_test

array([0, 0, 1, ..., 0, 0, 0])

In [23]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(ypred,y_test)

In [24]:
accuracy

0.8316166592028661